server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: AcmeAccountManager
  lifecycle:
    timeout-per-shutdown-phase: 10s
  datasource:
    url: jdbc:h2:~/acme-acc-manager-db;AUTO_SERVER=TRUE;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: password
    driverClassName: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      app-user: ${spring.datasource.username}
      app-password: ${spring.datasource.password}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true